# Generated by Django 2.0.3 on 2018-04-07 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20180321_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lego_club', models.BooleanField()),
                ('front_char', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.SmallIntegerField()),
                ('character_name', models.CharField(max_length=33)),
                ('character_unapproved_name', models.CharField(max_length=33)),
                ('is_name_rejected', models.BooleanField()),
                ('shirt_color', models.IntegerField()),
                ('shirt_style', models.IntegerField()),
                ('pants_color', models.IntegerField()),
                ('hair_style', models.IntegerField()),
                ('hair_color', models.IntegerField()),
                ('lh', models.IntegerField()),
                ('rh', models.IntegerField()),
                ('eyebrows', models.IntegerField()),
                ('eyes', models.IntegerField()),
                ('mouth', models.IntegerField()),
                ('last_zone', models.IntegerField()),
                ('last_instance', models.IntegerField()),
                ('last_clone', models.IntegerField()),
                ('last_login', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
