# Generated by Django 2.0.3 on 2018-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180406_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='address',
            field=models.GenericIPAddressField(),
        ),
    ]
