# Generated by Django 2.0.3 on 2018-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180506_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
