# Generated by Django 2.0.3 on 2018-05-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180511_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
