# Generated by Django 2.0.3 on 2018-05-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180512_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.Account')),
                ('token', models.BinaryField()),
                ('ip', models.GenericIPAddressField()),
                ('port', models.SmallIntegerField()),
            ],
        ),
    ]
