# Generated by Django 2.0.3 on 2018-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='clone',
            field=models.IntegerField(default=0),
        ),
    ]
