# Generated by Django 2.0.3 on 2018-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_session_clone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='clone',
            field=models.IntegerField(null=True),
        ),
    ]
