# Generated by Django 2.0.3 on 2018-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180513_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
