# Generated by Django 2.0.3 on 2018-05-26 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_mission_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 5, 26, 12, 47, 14, 95527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
