# Generated by Django 2.0.3 on 2018-05-26 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20180526_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 12, 55, 13, 110205, tzinfo=utc)),
        ),
    ]
