# Generated by Django 2.0.3 on 2018-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20180526_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
