# Generated by Django 2.0.3 on 2018-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('game', '0019_auto_20180526_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='id',
            new_name='objid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='front_character',
        ),
        migrations.RemoveField(
            model_name='character',
            name='slot',
        ),
        migrations.AddField(
            model_name='character',
            name='is_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
