# Generated by Django 2.0.3 on 2018-06-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_session_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Character'),
        ),
    ]
